apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mall-demo-docker
spec:
  encryptedData:
    .dockerconfigjson: AQAG/W+GTz53gQ1PhvDQEyDz5y3WRBhBIKHthUp301FqA60qwiZabWJ017duVubJ3WuQb5+Q+fnQehCniYMTUURL4jWmY8OFkVXdthy4HV7MpSNW89QmvjwDt1VZ+eINg86AJ4A0yr9X05gPFlIzxKPspFLrb8iG92fiCV4E02JgXTbcWbEUTMqxWYnIxGy7D4JJYvdIbo3s6Mtz1u0OXz2SmQZG9cbKNnUcDEIc6SxBcR3nhynYyXXeMTtdXk1eO+K1nEMjMlSc/kHDikK38e9KRVxKHFAqb2iItO0Ayw+avP0Qo0ISF5o+WPNmbhYy6nwzSBqtNMw72bpWu2NaAFgH1fIex55FZJnyQ/b222+cBl7Dbxjrq2nZzRs4885Ux4lsrHfngFjGl7AOR5LPx5RHasY0gqgztg0Bd7MdJWe7fFR6FwgBTAW3l5FEbwXkiT5yEt2zCAEvLiP4fa3BuXDxmTURD/hvW29OftuSc7WSsDEZ5qk5QrHrmsHbv9lO4pInYbPTKcNSQjV39VvldX7KYS4xocw7sCUG//v8kG6byeNJzeKHX8InD4I82kKHNkAN8g3ZQMt37u8DqF0Pqx7qxTKoPvJi42mx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mall-demo-docker
    type: kubernetes.io/dockerconfigjson
