mall-admin:
  env:
    - name: ENV_NAME
      value: main
    - name: ENV_DOMAIN
      value: mall-demo-i6n8k4bas.forkmain.cloud
  fullnameOverride: mall-admin
  image:
    repository: ghcr.io/hongchaodeng/mall
    tag: df3fa13
  imagePullSecrets:
    - name: mall-demo-docker
  ingress:
    className: nginx
    enabled: true
    hosts:
      - host: mall-demo-i6n8k4bas.forkmain.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
  nocalhost:
    command:
      debug:
        - ""
      run:
        - ""
    configPath: conf/nocalhost.yaml
    env: null
    gitURL: https://github.com/hongchaodeng/mall.git
    hotReload: false
    image: maven:3.8.6-jdk-11
    language: null
    patches: null
    persistentVolumeDirs:
      - capacity: 20Gi
        path: /home/nocalhost-dev
    remoteDebugPort: 9009
  service:
    port: 8080
    targetPort: 8080
